In [1]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import OneHotEncoder


In [2]:
data = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue']
})

In [3]:
ohe = OneHotEncoder(sparse_output=False)

In [9]:
encoded_data = ohe.fit_transform(data[["Color"]])

In [6]:
print(encoded_data)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [10]:
encoded_df = pd.DataFrame(encoded_data, columns=ohe.get_feature_names_out(['Color']))

In [11]:
print(encoded_df)

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0
